apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolngfe
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  selector:
    matchLabels:
      app: school
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: school
        tier: frontend
        track: stable
        timestamp: timestamptimestamp_ph_4
    spec:
      containers:
        - name: schoolngfectn
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 90
            timeoutSeconds: 40
#          readinessProbe:
#            httpGet:
#              port: 8080
#              path: /actuator/health
#            initialDelaySeconds: 20
#            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 5
            timeoutSeconds: 4
