apiVersion: apps/v1
kind: Deployment
metadata:
  name: schoolngfe
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'until wget schoolbe:8080/api/version/{{ .Values.backend.image.version }}; do echo waiting for myservice; sleep 2; done;']  
  selector:
    matchLabels:
      app: school
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: school
        tier: frontend
        track: stable
        timestamp: 2_timestamptimestamp_ph
    spec:
      containers:
        - name: schoolngfectn
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 90
            timeoutSeconds: 40
          readinessProbe:
#          readinessProbe:
#            exec:
#              command:
#              - wget
#              - -q
#              - schoolbe:8080/actuator/health
#              - -O
#              - health
          readinessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 5
            timeoutSeconds: 4
