apiVersion: v1
kind: Service
metadata:
  name: schoolngfe
spec:
  selector:
    app: school
    tier: frontend
  ports:
    - protocol: "TCP"
      nodePort: 31122
      port: 80
      targetPort: 80
  type: LoadBalancer
